# Generated by Django 5.1.2 on 2025-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("designer_name", models.CharField(max_length=100)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="designs/"),
                ),
                ("background_image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
