# Generated by Django 5.1.2 on 2025-05-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_design"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="background_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="design",
            name="background_image_url",
        ),
    ]
