# Generated by Django 5.1.2 on 2025-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_background_image_design_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="designer_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="design",
            name="image",
            field=models.ImageField(default=3, upload_to="design_images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="design",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
