# Generated by Django 5.1.2 on 2025-05-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_design_designer_name_alter_design_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("specialization", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="designers/")),
            ],
        ),
    ]
