# Generated by Django 5.1.2 on 2025-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_designer"),
    ]

    operations = [
        migrations.AddField(
            model_name="designer",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
