# Generated by Django 5.1.2 on 2025-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_designer_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="design",
            name="image",
            field=models.ImageField(upload_to="designs/"),
        ),
    ]
