# Generated by Django 5.1.2 on 2025-05-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_design_is_approved_alter_design_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteriorRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("Living Room", "Living Room"),
                            ("Bedroom", "Bedroom"),
                            ("Kitchen", "Kitchen"),
                            ("Office", "Office"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("style_preference", models.CharField(max_length=100)),
                ("budget", models.IntegerField()),
                ("color_scheme", models.CharField(max_length=100)),
                ("requirements", models.TextField()),
                ("services", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
