# Generated by Django 5.1.2 on 2025-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_interiorrequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("Living Room", "Living Room"),
                            ("Bedroom", "Bedroom"),
                            ("Kitchen", "Kitchen"),
                            ("Office", "Office"),
                            ("Commercial", "Commercial"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("Modern", "Modern"),
                            ("Traditional", "Traditional"),
                            ("Minimalist", "Minimalist"),
                            ("Industrial", "Industrial"),
                            ("Bohemian", "Bohemian"),
                        ],
                        max_length=50,
                    ),
                ),
                ("budget", models.IntegerField()),
                ("services", models.CharField(max_length=200)),
                ("timeline", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="InteriorRequirement",
        ),
    ]
